variables:
    MINIO_URL: minio-ss.oxs.cz
    DOMAIN_PROD: sedu.cz
    DOMAIN_DEV: $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_NAME.static.xsika.cz

image: ondrejsika/ci

stages:
    - build
    - deploy

job_build:
    stage: build
    script:
        - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
        - docker build -t $CI_REGISTRY_IMAGE .
        - docker push $CI_REGISTRY_IMAGE

job_deploy:
    stage: deploy
    only:
        - master
    variables:
        GIT_STRATEGY: none
    script:
        - curl -s "$SOD_URL/api/v1/deploy/docker/?image=$CI_REGISTRY_IMAGE&domain=$PROD_DOMAIN&token=$SOD_TOKEN&registry=$CI_REGISTRY&registry_user=$CI_REGISTRY_USER&registry_password=$CI_REGISTRY_PASSWORD"
    environment:
        name: $PROD_DOMAIN
        url: https://$PROD_DOMAIN
