future: true

collections:
  course:
    output: true
    permalink: /kurzy/:slug.html
  event:
    output: true
    permalink: /terminy/:slug.html

defaults:
  - scope:
      path: ""
      type: "course"
    values:
      layout: "course"
  - scope:
      path: ""
      type: "event"
    values:
      layout: "event"
